# =============================================================================
# ALACRITTY CONFIGURATION - MODULAR SETUP
# Catppuccin Mocha with Golden Accents
# =============================================================================

[env]
TERM = "xterm-256color"

# =============================================================================
# WINDOW CONFIGURATION
# =============================================================================
[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 8, y = 8 }
dynamic_padding = false
decorations = "full"
opacity = 0.95
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }

# =============================================================================
# SCROLLING CONFIGURATION
# =============================================================================
[scrolling]
history = 10000
multiplier = 3

# =============================================================================
# FONT CONFIGURATION
# =============================================================================
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

# =============================================================================
# COLOR SCHEME - CATPPUCCIN MOCHA WITH GOLDEN ACCENTS
# =============================================================================
[colors]
draw_bold_text_with_bright_colors = true

# Primary colors
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

# Cursor colors (Golden theme)
[colors.cursor]
text = "#1e1e2e"
cursor = "#d4af37"  # Rich gold

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#f4d03f"  # Lighter gold

# Search colors (Golden highlights)
[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#d4af37"  # Golden focused match

# URL hints (Golden theme)
[colors.hints.start]
foreground = "#1e1e2e"
background = "#d4af37"  # Rich gold

[colors.hints.end]
foreground = "#1e1e2e"
background = "#f4d03f"  # Lighter gold

# Selection colors (Golden tint)
[colors.selection]
text = "#1e1e2e"
background = "#e6c547"  # Golden selection

# Standard color palette
[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#d4af37"     # Rich golden yellow
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f4d03f"     # Bright golden yellow
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#b8941f"     # Muted golden yellow
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

# =============================================================================
# TERMINAL BEHAVIOR
# =============================================================================
[bell]
animation = "EaseOutExpo"
duration = 0
color = "#d4af37"  # Golden bell

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = "None"
blink_interval = 750
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "CopyPaste"

# =============================================================================
# MOUSE CONFIGURATION
# =============================================================================
[mouse]
hide_when_typing = false

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"

# =============================================================================
# URL HINTS CONFIGURATION
# =============================================================================
[hints]
enabled = [
    { 
        regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001f\u007f-\u009f<>\"\\s{-}\\^⟨⟩`]+", 
        hyperlinks = true, 
        command = "xdg-open", 
        post_processing = true, 
        mouse = { enabled = true, mods = "None" }, 
        binding = { key = "U", mods = "Control|Shift" } 
    }
]

# =============================================================================
# KEYBOARD BINDINGS
# =============================================================================

# -----------------------------------------------------------------------------
# CLIPBOARD OPERATIONS
# -----------------------------------------------------------------------------
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

# -----------------------------------------------------------------------------
# FONT SIZE CONTROLS
# -----------------------------------------------------------------------------
[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "NumpadAdd"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "NumpadSubtract"
mods = "Control"
action = "DecreaseFontSize"

# -----------------------------------------------------------------------------
# VI MODE BINDINGS
# -----------------------------------------------------------------------------
[[keyboard.bindings]]
key = "Space"
mods = "Shift|Control"
mode = "~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Space"
mods = "Shift|Control"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "Escape"
mode = "Vi|~Search"
action = "ClearSelection"

[[keyboard.bindings]]
key = "I"
mode = "Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "I"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "C"
mods = "Control"
mode = "Vi|~Search"
action = "ToggleViMode"

# -----------------------------------------------------------------------------
# SEARCH MODE BINDINGS
# -----------------------------------------------------------------------------
[[keyboard.bindings]]
key = "Return"
mode = "Search|Vi"
action = "SearchConfirm"

[[keyboard.bindings]]
key = "Escape"
mode = "Search"
action = "SearchCancel"

[[keyboard.bindings]]
key = "C"
mods = "Control"
mode = "Search"
action = "SearchCancel"

[[keyboard.bindings]]
key = "U"
mods = "Control"
mode = "Search"
action = "SearchClear"

[[keyboard.bindings]]
key = "W"
mods = "Control"
mode = "Search"
action = "SearchDeleteWord"

[[keyboard.bindings]]
key = "P"
mods = "Control"
mode = "Search"
action = "SearchHistoryPrevious"

[[keyboard.bindings]]
key = "N"
mods = "Control"
mode = "Search"
action = "SearchHistoryNext"

[[keyboard.bindings]]
key = "Up"
mode = "Search"
action = "SearchHistoryPrevious"

[[keyboard.bindings]]
key = "Down"
mode = "Search"
action = "SearchHistoryNext"

[[keyboard.bindings]]
key = "Return"
mode = "Search|~Vi"
action = "SearchFocusNext"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
mode = "Search|~Vi"
action = "SearchFocusPrevious"

# -----------------------------------------------------------------------------
# WINDOW MANAGEMENT
# -----------------------------------------------------------------------------
[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

# -----------------------------------------------------------------------------
# CUSTOM BINDINGS (Add your own here)
# -----------------------------------------------------------------------------

# Example: Open new terminal in same directory
# [[keyboard.bindings]]
# key = "Return"
# mods = "Super|Shift"
# action = "SpawnNewInstance"

# Example: Quick config reload
# [[keyboard.bindings]]
# key = "R"
# mods = "Control|Shift"
# action = "ReloadConfig"
